# -*- coding: utf-8 -*-
"""Generate docs/quote_support_field_map.csv (UTF-8, no BOM)."""
import csv
from pathlib import Path

ROWS: list[list[str]] = []


def r(
    category: str,
    table: str,
    field: str,
    korean: str,
    role: str,
    dtype: str,
    example: str,
    formula: str,
    stored_at: str,
    editor: str,
    api: str,
    files: str,
    dashboard: str,
    label: str,
    fallback: str,
    notes: str,
) -> None:
    ROWS.append(
        [
            category,
            table,
            field,
            korean,
            role,
            dtype,
            example,
            formula,
            stored_at,
            editor,
            api,
            files,
            dashboard,
            label,
            fallback,
            notes,
        ]
    )


HEADER = [
    "구분",
    "테이블명",
    "필드명",
    "한글명",
    "역할정의",
    "데이터 타입",
    "값 예시",
    "계산식",
    "저장 시점",
    "수정 주체",
    "사용하는 API",
    "사용하는 파일/컴포넌트",
    "표시되는 대시보드",
    "표시 라벨",
    "fallback 우선순위",
    "주의사항",
]

# --- applications ---
r(
    "DB",
    "applications",
    "target_normal_price",
    "희망 일반견적(목표가)",
    "고객 신청 시 희망하는 일반견적 금액(원)",
    "bigint",
    "600000",
    "",
    "견적요청 제출",
    "고객",
    "POST public application",
    "app/(site)/page.tsx; lib/admin-application-detail-sections.ts",
    "클라이언트·파트너·어드민",
    "일반견적가 목표(클라 LABEL.targetNormalPrice); 우선마감 목표가(파트너)",
    "target_normal_price -> quote.price(견적 미제출 시)",
    "실제 일반견적가는 driver_quotes.price",
)
r(
    "DB",
    "applications",
    "target_member_price",
    "희망 할인견적(목표가)",
    "고객 신청 시 희망 지원금 할인가 목표(원)",
    "bigint",
    "400000",
    "",
    "견적요청 제출",
    "고객",
    "POST public application",
    "app/(site)/page.tsx",
    "클라이언트",
    "지원금 할인가 목표",
    "target_member_price",
    "preferred_quote_types에 support 포함 시",
)
r(
    "DB",
    "applications",
    "preferred_quote_types",
    "희망견적유형",
    "고객이 받고 싶은 견적 유형 배열",
    "text[]",
    "{normal,support}",
    "",
    "견적요청 제출",
    "고객",
    "",
    "app/(site)/page.tsx; PartnerCallExpandPanel",
    "파트너",
    "희망견적유형; 일반견적/할인견적",
    "",
    "normal=일반견적 support=할인견적(지원금)",
)
r(
    "DB",
    "applications",
    "quote_status",
    "견적 라이프사이클 상태",
    "견적 수집·마감·자동선정·최종확정·계약 등",
    "text",
    "collecting|final_selected|completed",
    "",
    "상태 전이(크론·API·매칭)",
    "시스템·어드민·고객",
    "GET /api/client/quotes; GET /api/admin/application-detail",
    "lib/quote-auction.ts; lib/client-application-view-model.ts",
    "클라이언트·파트너·어드민·스폰서",
    "견적요청중/자동마감/매칭완료 탭",
    "quote_status",
    "lib/quote-auction QuoteStatus 참고",
)
r(
    "DB",
    "applications",
    "extension_round",
    "연장회차",
    "견적 미수집 시 자동 연장 횟수(0~6)",
    "integer",
    "2",
    "",
    "연장 크론",
    "시스템",
    "",
    "lib/quote-auction.ts; lib/quote-support-display-model.ts",
    "파트너·어드민·공통",
    "연장 회차; 연장회차",
    "applications.extension_round -> extension_count",
    "QUOTE_MAX_EXTENSION_ROUNDS=6",
)
r(
    "DB",
    "applications",
    "final_selected_quote_id",
    "최종 선택 견적 ID",
    "매칭 확정된 견적 행 UUID",
    "uuid",
    "(uuid)",
    "",
    "매칭 확정·자동확정",
    "고객·시스템",
    "PATCH /api/client/quotes",
    "lib/admin-application-detail-sections.ts; app/api/client/quotes/route.ts",
    "전체",
    "선택 견적(매칭 기준)",
    "member: driver_quotes.id / guest: guest_driver_quotes.id",
    "final_selected_quote_source와 쌍",
)
r(
    "DB",
    "applications",
    "final_selected_quote_source",
    "최종 선택 견적 출처",
    "member(제휴) 또는 guest(일반기사)",
    "text",
    "member|guest",
    "",
    "매칭 확정",
    "고객·시스템",
    "PATCH /api/client/quotes",
    "lib/admin-application-detail-sections.ts",
    "어드민·클라이언트",
    "제휴기사 견적/일반기사 견적",
    "final_selected_quote_source",
    "guest 아니면 member",
)
r(
    "DB",
    "applications",
    "selected_price_type",
    "선택 견적가 종류",
    "고객 매칭 시 선택한 가격 유형",
    "text",
    "normal|support_planned|support_confirmed",
    "",
    "고객 매칭 확정",
    "고객",
    "PATCH /api/client/quotes",
    "lib/selected-price-display.ts; lib/quote-support-display-model.ts",
    "클라이언트·어드민·파트너",
    "일반견적가/지원금 할인 예상가/지원금 할인 적용가",
    "selected_price_type -> client_price_selection_kind -> 금액 추론",
    "sql/application_selected_price.sql",
)
r(
    "DB",
    "applications",
    "selected_price_label",
    "선택 견적가 표시명",
    "저장 당시 UI 라벨",
    "text",
    "지원금 할인 적용가",
    "",
    "고객 매칭 확정",
    "고객",
    "PATCH /api/client/quotes",
    "lib/selected-price-display.ts",
    "전체",
    "매칭견적가·선택 견적",
    "selected_price_label (type 없을 때)",
    "type과 불일치 시 금액 보정",
)
r(
    "DB",
    "applications",
    "selected_price",
    "선택 견적(금액)",
    "고객 매칭 확정 견적 금액(원)",
    "bigint",
    "500000",
    "",
    "고객 매칭 확정",
    "고객",
    "PATCH /api/client/quotes",
    "ClientMatchedPricePanel; ApplicationDetailMatchedPanel",
    "클라이언트·어드민",
    "매칭금액·선택 견적",
    "selected_price + selected_price_type",
    "inferSelectedPriceTypeFromAmounts 보정",
)
r(
    "DB",
    "applications",
    "client_price_selection_kind",
    "레거시 선택 종류",
    "구 필드; selected_price_type과 동의어",
    "text",
    "support_confirmed_selected",
    "",
    "매칭 확정(레거시)",
    "고객",
    "PATCH /api/client/quotes",
    "lib/selected-price-display.ts",
    "",
    "",
    "selected_price_type -> client_price_selection_kind",
    "신규는 selected_price_type 권장",
)
r(
    "DB",
    "applications",
    "support_breakdown_snapshot",
    "신청 단위 지원 스냅샷",
    "매칭 직후 규칙·예상 지원 JSON",
    "jsonb",
    "{planned_total_support:500000,...}",
    "buildPlannedSupportBreakdownSnapshot()",
    "스폰서 preapprove·매칭",
    "시스템",
    "GET /api/client/quotes",
    "lib/support-breakdown-snapshot.ts; lib/application-approved-support.ts",
    "클라이언트·어드민",
    "예상 지원금(견적 전)",
    "support_breakdown_snapshot.planned_total_support",
    "driver_quotes.support_breakdown과 별도",
)
r(
    "DB",
    "applications",
    "sponsor_support_status",
    "스폰서 지원 요약 상태",
    "preapproval 집계 상태",
    "text",
    "none|preapproved|approved|rejected|mixed",
    "deriveStatus(preapprovals)",
    "preapproval 변경",
    "시스템",
    "GET /api/client/quotes; admin detail",
    "lib/sponsor-support.ts; lib/admin-sponsor-confirmed.ts",
    "전체",
    "지원금 검토중/지원금 확정(클라)",
    "sponsor_support_status=approved -> 지원확정",
    "견적별 status와 구분",
)
r(
    "DB",
    "applications",
    "sponsor_approved_support_amount",
    "신청 확정 지원금 합계",
    "승인 preapproval 금액 합",
    "bigint",
    "500000",
    "sum(approved_support_amount where status=approved)",
    "스폰서 승인·집계",
    "시스템",
    "admin detail; partner calls",
    "lib/application-approved-support.ts",
    "어드민·파트너",
    "확정 지원금",
    "snapshot.confirmed_total_support -> sponsor_approved_support_amount",
    "",
)
r(
    "DB",
    "applications",
    "sponsor_preapproved_count",
    "가승인 건수",
    "preapproved 건수",
    "integer",
    "1",
    "",
    "집계",
    "시스템",
    "admin detail",
    "lib/admin-application-detail-sections.ts",
    "어드민",
    "",
    "",
    "",
)
r(
    "DB",
    "applications",
    "sponsor_approved_count",
    "승인 건수",
    "approved 건수",
    "integer",
    "1",
    "",
    "집계",
    "시스템",
    "admin detail",
    "lib/admin-application-detail-sections.ts",
    "어드민",
    "",
    "",
    "",
)
r(
    "DB",
    "applications",
    "sponsor_rejected_count",
    "거절 건수",
    "rejected/cancelled/expired",
    "integer",
    "0",
    "",
    "집계",
    "시스템",
    "admin detail",
    "lib/admin-application-detail-sections.ts",
    "어드민",
    "",
    "",
    "",
)
r(
    "코드전용",
    "applications (API 병합)",
    "estimated_support_amount",
    "신청 예상 지원금",
    "API/build 시 병합; DB 컬럼 없을 수 있음",
    "number",
    "500000",
    "resolveApplicationEstimatedSupportTotal()",
    "조회 시",
    "시스템",
    "admin application-detail",
    "lib/application-approved-support.ts",
    "어드민",
    "예상 지원금",
    "snapshot.planned_total_support -> sponsor.estimated",
    "DB 미존재/코드 전용 가능",
)
r(
    "코드전용",
    "applications (API 병합)",
    "approved_support_amount",
    "신청 확정 지원금",
    "API/build 병합",
    "number",
    "500000",
    "resolveApplicationApprovedSupportTotal()",
    "조회 시",
    "시스템",
    "admin application-detail",
    "lib/application-approved-support.ts",
    "어드민",
    "확정 지원금",
    "snapshot.confirmed -> sponsor_approved_support_amount",
    "DB 미존재/코드 전용 가능",
)

# --- driver_quotes ---
r(
    "DB",
    "driver_quotes",
    "price",
    "일반견적가",
    "제휴기사 일반 견적 금액(원)",
    "integer",
    "600000",
    "",
    "견적 제출/수정",
    "제휴기사",
    "POST /api/partner/quotes",
    "lib/support-calculation.ts; lib/quote-support-display-model.ts",
    "클라·파트너·어드민·스폰서",
    "일반견적가",
    "breakdown.normal_price -> price -> target_normal_price",
    "",
)
r(
    "DB",
    "driver_quotes",
    "sponsor_quote_enabled",
    "지원금 견적 여부",
    "지원금 할인가 동시 제시",
    "boolean",
    "true",
    "",
    "견적 제출",
    "제휴기사",
    "POST /api/partner/quotes",
    "lib/support-calculation.ts",
    "파트너",
    "",
    "sponsor_quote_enabled",
    "false면 breakdown 미생성",
)
r(
    "DB",
    "driver_quotes",
    "support_settlement_type",
    "지원금 정산모드",
    "client_priority | ratio",
    "text",
    "client_priority",
    "",
    "견적 제출",
    "제휴기사",
    "partner quotes; sponsor confirm",
    "lib/support-calculation.ts",
    "파트너",
    "고객 지원금 우선보장/비율정산",
    "breakdown.support_mode -> support_settlement_type",
    "확정 분배 공식 결정",
)
r(
    "DB",
    "driver_quotes",
    "support_breakdown",
    "지원금 breakdown",
    "규칙·예상/확정 스냅샷 JSON",
    "jsonb",
    "SupportBreakdownSnapshot",
    "buildPlannedSupportBreakdownSnapshot; applyConfirmedToSupportBreakdownSnapshot",
    "견적 제출·스폰서 확정",
    "시스템",
    "partner/client/admin APIs",
    "lib/support-breakdown-snapshot.ts",
    "전체",
    "예상/확정 지원·할인가 등",
    "support_breakdown 최우선",
    "sponsor_rules 변경 후 불변",
)
r(
    "DB",
    "driver_quotes",
    "planned_total_support",
    "총 예정 지원금 / 예상 지원금",
    "견적 제출 시 고정 총 예상",
    "bigint",
    "500000",
    "resolvePlannedTotalSupport",
    "견적 제출",
    "시스템",
    "partner quotes",
    "lib/quote-support-snapshot.ts",
    "전체",
    "예상 지원금; 총 예상 지원금",
    "breakdown.planned_total_support -> planned_total_support -> preapproved_support_amount",
    "승인 후 덮어쓰지 않음",
)
r(
    "DB",
    "driver_quotes",
    "planned_customer_support",
    "고객 예정 지원금 / 고객 예상 지원금",
    "고객 예상 지원금",
    "bigint",
    "300000",
    "규칙·폼",
    "견적 제출",
    "시스템·기사",
    "partner quotes",
    "lib/support-calculation.ts",
    "전체",
    "고객 예상 지원금",
    "breakdown -> planned_customer_support -> customer_support_amount",
    "",
)
r(
    "DB",
    "driver_quotes",
    "planned_driver_support",
    "기사 예정 지원금 / 기사 예상 지원금",
    "제휴기사 예상 지원금",
    "bigint",
    "200000",
    "max(total - customer - extensionPlanned, 0)",
    "견적 제출",
    "시스템",
    "partner quotes",
    "lib/support-calculation.ts",
    "전체",
    "기사 예상 지원금",
    "breakdown -> planned_driver_support -> driver_support_amount",
    "",
)
r(
    "DB",
    "driver_quotes",
    "planned_discount_price",
    "지원금 할인 예정가 / 지원금 할인 예상가",
    "예정 할인 적용가",
    "bigint",
    "300000",
    "max(normal - customer - extensionPlanned, 0)",
    "견적 제출",
    "시스템",
    "partner quotes",
    "lib/support-calculation.ts",
    "전체",
    "지원금 할인 예상가",
    "breakdown.planned_discount_price -> member_price",
    "",
)
r(
    "DB",
    "driver_quotes",
    "confirmed_total_support",
    "총 확정 지원금 / 확정 지원금",
    "스폰서 승인 총액",
    "bigint",
    "500000",
    "resolveConfirmedTotalSupport",
    "스폰서 확정",
    "시스템",
    "sponsor dashboard",
    "lib/support-calculation.ts",
    "전체",
    "확정 지원금",
    "breakdown.confirmed_total_support -> confirmed_total_support -> approved_support_amount",
    "",
)
r(
    "DB",
    "driver_quotes",
    "confirmed_customer_support",
    "고객 확정 지원금",
    "확정 고객 몫",
    "bigint",
    "300000",
    "client_priority: min(planned_customer,total); ratio: round(planned_customer*total/planned_total); derive: normal-final_discount-extension",
    "스폰서 확정",
    "시스템",
    "sponsor confirm",
    "lib/support-calculation.ts",
    "전체",
    "고객 확정 지원금",
    "breakdown -> confirmed_customer_support -> final_customer_support_amount",
    "CONFIRMED_CUSTOMER_DERIVE_FORMULA",
)
r(
    "DB",
    "driver_quotes",
    "confirmed_driver_support",
    "기사 확정 지원금",
    "확정 기사 몫(연장 차감 전)",
    "bigint",
    "200000",
    "confirmed_total - confirmed_customer (연장 전)",
    "스폰서 확정",
    "시스템",
    "sponsor confirm",
    "lib/quote-support-display-model.ts",
    "전체",
    "기사 확정 지원금",
    "breakdown -> confirmed_driver_support -> final_driver_support_amount",
    "",
)
r(
    "DB",
    "driver_quotes",
    "confirmed_discount_price",
    "지원금 할인 적용가",
    "확정 할인가",
    "bigint",
    "300000",
    "max(normal - customer_confirmed - extension_confirmed, 0)",
    "스폰서 확정",
    "시스템",
    "sponsor confirm",
    "lib/support-calculation.ts",
    "전체",
    "지원금 할인 적용가",
    "breakdown.final_discount_price -> final_member_price",
    "",
)
r(
    "DB",
    "driver_quotes",
    "extension_support_amount",
    "확정 연장 지원금",
    "연장 시 고객 연장 지원",
    "bigint",
    "40000",
    "calculateExtension(partnerConfirmed, extension_round) 또는 round(partnerConfirmed*0.2); 예상: extensionPlannedFromPartnerSupport(partnerPlanned, round)",
    "스폰서 확정·연장",
    "시스템",
    "partner quotes",
    "lib/support-calculation.ts",
    "전체",
    "확정 연장 지원금; 연장 지원금",
    "breakdown.confirmed_extension_support -> extension_support_amount",
    "1회차 예상연장 20% 2회차+ 40% (기사 예정 기준)",
)
r(
    "DB",
    "driver_quotes",
    "preapproved_support_amount",
    "총 예정 지원금(레거시)",
    "planned_total_support 이전명",
    "bigint",
    "500000",
    "= planned_total_support",
    "견적 제출",
    "시스템",
    "partner quotes",
    "lib/support-calculation.ts",
    "",
    "",
    "planned_total_support -> preapproved_support_amount",
    "레거시",
)
r(
    "DB",
    "driver_quotes",
    "approved_support_amount",
    "총 확정 지원금(레거시)",
    "confirmed_total_support 이전명",
    "bigint",
    "500000",
    "= confirmed_total_support",
    "스폰서 확정",
    "시스템",
    "",
    "lib/support-calculation.ts",
    "",
    "",
    "confirmed_total_support -> approved_support_amount",
    "",
)
r(
    "DB",
    "driver_quotes",
    "customer_support_amount",
    "고객 예정 지원금(레거시)",
    "planned_customer_support 이전",
    "bigint",
    "300000",
    "",
    "견적 제출",
    "기사",
    "",
    "lib/support-calculation.ts",
    "",
    "",
    "planned_customer_support -> customer_support_amount",
    "",
)
r(
    "DB",
    "driver_quotes",
    "driver_support_amount",
    "기사 예정 지원금(레거시)",
    "planned_driver_support 이전",
    "bigint",
    "200000",
    "total-customer-extension",
    "견적 제출",
    "시스템",
    "",
    "lib/support-calculation.ts",
    "",
    "",
    "",
    "",
)
r(
    "DB",
    "driver_quotes",
    "final_customer_support_amount",
    "고객 확정 지원금(레거시)",
    "confirmed_customer_support 이전",
    "bigint",
    "300000",
    "",
    "스폰서 확정",
    "시스템",
    "",
    "lib/support-calculation.ts",
    "",
    "",
    "",
    "",
)
r(
    "DB",
    "driver_quotes",
    "final_driver_support_amount",
    "기사 확정 지원금(레거시)",
    "confirmed_driver_support 이전",
    "bigint",
    "200000",
    "",
    "스폰서 확정",
    "시스템",
    "",
    "lib/support-calculation.ts",
    "",
    "",
    "",
    "",
)
r(
    "DB",
    "driver_quotes",
    "member_price",
    "지원금 할인 예정가(레거시)",
    "planned_discount_price 이전",
    "bigint",
    "300000",
    "normal-customer-extension",
    "견적 제출",
    "시스템",
    "",
    "lib/support-calculation.ts",
    "전체",
    "지원금 할인 예상가",
    "member_price -> planned_discount_price",
    "",
)
r(
    "DB",
    "driver_quotes",
    "final_member_price",
    "지원금 할인 적용가(레거시)",
    "confirmed_discount_price 이전",
    "bigint",
    "300000",
    "",
    "스폰서 확정",
    "시스템",
    "",
    "lib/support-calculation.ts",
    "전체",
    "지원금 할인 적용가",
    "final_member_price -> confirmed_discount_price",
    "",
)
r(
    "DB",
    "driver_quotes",
    "estimated_support_amount",
    "예상 지원금(폼)",
    "인원 기반 폼 계산",
    "bigint",
    "400000",
    "estimateSponsorSupport",
    "견적 제출",
    "시스템",
    "partner quotes",
    "lib/partner-call-view-model.ts",
    "파트너",
    "예상 지원금",
    "estimated_support_amount -> planned_total",
    "",
)
r(
    "DB",
    "driver_quotes",
    "support_discount_amount",
    "고객 지원 반영액",
    "기사 입력 고객 지원",
    "bigint",
    "300000",
    "",
    "견적 제출",
    "제휴기사",
    "partner quotes",
    "lib/partner-call-view-model.ts",
    "",
    "",
    "customer_support_amount 연동",
    "",
)
r(
    "DB",
    "driver_quotes",
    "sponsor_support_status",
    "견적별 스폰서 상태",
    "지원 승인 mirror",
    "text",
    "approved",
    "",
    "집계",
    "시스템",
    "GET /api/client/quotes",
    "lib/client-application-view-model.ts",
    "클라이언트",
    "지원금 확정/검토중",
    "quote -> application.sponsor_support_status",
    "",
)
r(
    "확인 필요",
    "driver_quotes",
    "total_planned_support",
    "총 예상 지원금(별칭)",
    "admin select alias",
    "bigint",
    "",
    "",
    "",
    "",
    "admin detail",
    "lib/admin-application-detail-sections.ts",
    "어드민",
    "예상 지원금",
    "total_planned_support vs planned_total_support",
    "실DB 컬럼명은 planned_total_support",
)
r(
    "확인 필요",
    "driver_quotes",
    "total_confirmed_support",
    "총 확정 지원금(별칭)",
    "admin select alias",
    "bigint",
    "",
    "",
    "",
    "",
    "admin detail",
    "lib/admin-member-quote-support-display.ts",
    "어드민",
    "확정 지원금",
    "confirmed_total_support",
    "",
)

# --- guest ---
r(
    "DB",
    "guest_driver_quotes",
    "price",
    "일반견적가(비회원)",
    "일반기사 견적 금액",
    "integer",
    "550000",
    "",
    "비회원 견적 제출",
    "일반기사",
    "POST /api/guest/quotes",
    "app/api/guest/quotes/route.ts",
    "클라·어드민",
    "일반견적가; 일반기사 견적",
    "guest price only",
    "지원 breakdown 없음",
)

# --- sponsor_preapprovals ---
r(
    "DB",
    "sponsor_preapprovals",
    "status",
    "스폰서 매칭 상태",
    "preapproved|approved|rejected|...",
    "text",
    "preapproved",
    "",
    "매칭·승인",
    "스폰서·시스템",
    "GET /api/sponsor/dashboard",
    "lib/sponsor-preapproval.ts",
    "스폰서·어드민",
    "지원검토/지원확정",
    "status",
    "applications.sponsor_support_status 원천",
)
r(
    "DB",
    "sponsor_preapprovals",
    "estimated_support_amount",
    "예상 지원금",
    "규칙 기반 예상 총액",
    "bigint",
    "500000",
    "estimateSponsorSupport",
    "자동매칭",
    "시스템",
    "sponsor dashboard",
    "lib/sponsor-preapproval.ts",
    "스폰서",
    "예상 지원금",
    "preapproval.estimated_support_amount",
    "",
)
r(
    "DB",
    "sponsor_preapprovals",
    "approved_support_amount",
    "확정 지원금",
    "스폰서 확정 입력 총액",
    "bigint",
    "500000",
    "",
    "지원확정",
    "스폰서",
    "PATCH sponsor dashboard",
    "lib/sponsor-support.ts",
    "스폰서·어드민",
    "확정 지원금",
    "approved_support_amount -> driver confirmed",
    "",
)

# --- sponsor_rules ---
r(
    "DB",
    "sponsor_rules",
    "support_per_person",
    "인당 지원금",
    "규칙 인당",
    "bigint",
    "20000",
    "passengers*per_person capped by max",
    "규칙 저장",
    "스폰서",
    "/api/sponsor/dashboard",
    "lib/sponsor-rule-helpers.ts",
    "스폰서 설정",
    "인당 지원금",
    "rule -> estimate",
    "",
)
r(
    "DB",
    "sponsor_rules",
    "support_per_case",
    "건당 지원금",
    "규칙 건당",
    "bigint",
    "0",
    "",
    "규칙 저장",
    "스폰서",
    "/api/sponsor/dashboard",
    "lib/sponsor-rule-helpers.ts",
    "스폰서",
    "건당 지원금",
    "",
    "",
)
r(
    "DB",
    "sponsor_rules",
    "max_support_amount",
    "최대 지원금",
    "규칙 상한",
    "bigint",
    "800000",
    "min(산출, max)",
    "규칙 저장",
    "스폰서",
    "/api/sponsor/dashboard",
    "lib/sponsor-rule-helpers.ts",
    "스폰서",
    "최대 지원금",
    "",
    "",
)
r(
    "DB",
    "sponsor_rules",
    "target_groups",
    "지원단체",
    "단체유형 배열",
    "text[]",
    "{회사원/직장인}",
    "",
    "규칙 저장",
    "스폰서",
    "",
    "lib/organization-types.ts",
    "스폰서",
    "지원단체",
    "",
    "organization_type 매칭",
)

# --- sponsor_staff ---
r(
    "DB",
    "sponsor_staff",
    "name",
    "담당자 이름",
    "표시명",
    "text",
    "홍길동",
    "",
    "등록",
    "스폰서",
    "sponsor dashboard",
    "lib/admin-application-detail-sections.ts",
    "스폰서·어드민",
    "담당자",
    "",
    "",
)
r(
    "DB",
    "sponsor_staff",
    "assigned_regions",
    "담당지역",
    "지역 매칭",
    "text[]",
    "서울",
    "",
    "등록",
    "스폰서",
    "",
    "sql/sponsor_staff_assigned_regions.sql",
    "스폰서",
    "담당지역",
    "",
    "확인 필요(매칭 로직)",
)

# --- virtual sponsor_support ---
r(
    "코드전용",
    "(sponsor_support 객체)",
    "sponsor_support",
    "스폰서 지원 집계",
    "DB 테이블 없음; display input",
    "object",
    "{status,estimated_support_amount}",
    "getApprovedSponsorSupport()",
    "조회 시",
    "시스템",
    "admin detail",
    "lib/sponsor-support.ts; lib/quote-support-display-model.ts",
    "어드민(내부)",
    "",
    "sponsor_preapprovals 집계",
    "DB 미존재/코드 전용",
)

# --- support_breakdown JSON keys ---
_JSON_FIELDS = [
    (
        "planned_total_support",
        "예상 지원금",
        "총 예정",
        "500000",
        "resolvePlannedTotalSupport",
    ),
    (
        "planned_customer_support",
        "고객 예상 지원금",
        "고객 예정",
        "300000",
        "resolvePlannedCustomerSupport",
    ),
    (
        "planned_driver_support",
        "기사 예상 지원금",
        "기사 예정",
        "200000",
        "calculatePlannedDriverSupport(total,customer,extension)",
    ),
    (
        "planned_extension_support",
        "예상 연장 지원금",
        "예정 연장",
        "40000",
        "extensionPlannedFromPartnerSupport(partnerPlanned, extension_round)",
    ),
    (
        "planned_discount_price",
        "지원금 할인 예상가",
        "예정 할인가",
        "300000",
        "calculatePlannedDiscountPrice(normal,customer,extension)",
    ),
    (
        "confirmed_total_support",
        "확정 지원금",
        "총 확정",
        "500000",
        "resolveConfirmedTotalSupport",
    ),
    (
        "confirmed_customer_support",
        "고객 확정 지원금",
        "확정 고객",
        "300000",
        "calculateSupportDistribution 또는 derive",
    ),
    (
        "confirmed_driver_support",
        "기사 확정 지원금",
        "확정 기사",
        "200000",
        "confirmed_total - customer - extension",
    ),
    (
        "confirmed_extension_support",
        "확정 연장 지원금",
        "확정 연장",
        "40000",
        "calculateExtension(driverBeforeExtension, extension_round)",
    ),
    (
        "final_discount_price",
        "지원금 할인 적용가",
        "확정 할인",
        "300000",
        "max(normal-customer-extension,0)",
    ),
    (
        "normal_price",
        "일반견적가",
        "스냅샷 일반가",
        "600000",
        "quote.price",
    ),
    (
        "support_mode",
        "지원금 정산모드",
        "client_priority|ratio",
        "client_priority",
        "",
    ),
]
for field, kor, role, ex, formula in _JSON_FIELDS:
    r(
        "JSON",
        "driver_quotes.support_breakdown / applications.support_breakdown_snapshot",
        field,
        kor,
        role,
        "jsonb",
        ex,
        formula,
        "견적 제출·preapprove·스폰서 확정",
        "시스템",
        "partner/client/admin APIs",
        "lib/support-breakdown-snapshot.ts; lib/quote-support-display-model.ts",
        "전체",
        kor,
        f"support_breakdown.{field} 최우선",
        "QuoteSupportBreakdown camelCase는 API 런타임용",
    )

# --- QuoteSupportBreakdown runtime ---
_CAMEL = [
    ("totalPlannedSupport", "예상 지원금", "buildQuoteSupportBreakdown"),
    ("customerPlannedSupport", "고객 예상 지원금", "planned.customer"),
    ("partnerPlannedSupport", "기사 예상 지원금", "planned.driver"),
    ("supportDiscountPlannedPrice", "지원금 할인 예상가", "planned.discountPrice"),
    ("totalConfirmedSupport", "확정 지원금", "resolveConfirmedTotalSupport"),
    ("customerConfirmedSupport", "고객 확정 지원금", "confirmed customer"),
    ("partnerConfirmedSupport", "기사 확정 지원금", "confirmed driver"),
    ("supportDiscountAppliedPrice", "지원금 할인 적용가", "confirmed discount"),
    ("extensionSupport", "연장 지원금", "calculateExtensionSupport"),
    ("finalDiscountAppliedPrice", "최종 할인 적용가", "confirmed.finalPrice"),
    ("isConfirmed", "지원 확정 여부", "confirmedTotal>0"),
]
for field, kor, formula in _CAMEL:
    r(
        "코드전용",
        "QuoteSupportBreakdown",
        field,
        kor,
        "API 응답 계산 객체",
        "number|boolean",
        "",
        formula,
        "API 조회",
        "시스템",
        "client/partner/admin APIs",
        "lib/support-calculation.ts; lib/client-member-quote-payload.ts",
        "전체",
        f"클라:{kor}; 파트너:{kor}",
        "support_breakdown json -> buildQuoteSupportBreakdown",
        "DB 미존재/코드 전용",
    )

# --- Display model ---
_DISPLAY = [
    ("normal_price", "일반견적가", "클라·파트너·어드민·스폰서: 일반견적가"),
    ("planned_total_support", "예상 지원금", "지원검토: 예상 지원금"),
    ("confirmed_total_support", "확정 지원금", "지원확정: 확정 지원금"),
    ("planned_customer_support", "고객 예상 지원금", "고객 예상 지원금"),
    ("confirmed_customer_support", "고객 확정 지원금", "고객 확정 지원금"),
    ("planned_driver_support", "기사 예상 지원금", "기사 예상 지원금"),
    ("confirmed_driver_support", "기사 확정 지원금", "기사 확정 지원금"),
    ("extension_count", "연장회차", "연장회차"),
    ("planned_extension_support", "예상 연장 지원금", "예상 연장 지원금"),
    ("confirmed_extension_support", "확정 연장 지원금", "확정 연장 지원금"),
    ("planned_discount_price", "지원금 할인 예상가", "지원금 할인 예상가"),
    ("final_discount_price", "지원금 할인 적용가", "지원금 할인 적용가"),
    ("selected_price", "선택 견적", "매칭금액·선택 견적"),
    ("selected_price_label", "선택 견적 라벨", "일반견적가/지원금 할인 예상가/적용가"),
    ("support_stage", "지원단계", "지원검토|지원확정"),
    ("selected_price_type", "selected_price_type", "normal|support_planned|support_confirmed"),
]
for field, kor, labels in _DISPLAY:
    r(
        "코드전용",
        "QuoteSupportDisplayModel",
        field,
        kor,
        "buildQuoteSupportDisplayModel 출력",
        "mixed",
        "",
        "lib/quote-support-display-model.ts pickAmount/formula",
        "렌더 시",
        "시스템",
        "대시보드 API",
        "lib/quote-support-display-model.ts; SupportQuoteBreakdown.tsx",
        "클라·파트너·스폰서·어드민",
        labels,
        "breakdown -> quote -> application/sponsor",
        "DB 미존재/코드 전용",
    )

# --- API-only ---
r(
    "코드전용",
    "API 응답",
    "support_discount_planned_price",
    "지원금 할인 예상가",
    "클라이언트 견적 JSON",
    "number",
    "300000",
    "QuoteSupportBreakdown.supportDiscountPlannedPrice",
    "API 매핑",
    "시스템",
    "GET /api/client/quotes",
    "lib/client-member-quote-payload.ts",
    "클라이언트",
    "지원금 할인 예상가",
    "breakdown -> member_price",
    "DB 미존재/코드 전용",
)
r(
    "코드전용",
    "API 응답",
    "support_discount_applied_price",
    "지원금 할인 적용가",
    "클라이언트 견적 JSON",
    "number",
    "300000",
    "supportDiscountAppliedPrice",
    "API 매핑",
    "시스템",
    "GET /api/client/quotes",
    "lib/client-member-quote-payload.ts",
    "클라이언트",
    "지원금 할인 적용가",
    "confirmed_discount_price",
    "DB 미존재/코드 전용",
)

r(
    "확인 필요",
    "applications",
    "final_selected_guest_quote_id",
    "최종 선택 비회원 견적 ID",
    "별도 컬럼 없음; final_selected_quote_id + source=guest로 표현",
    "-",
    "-",
    "final_selected_quote_id when final_selected_quote_source=guest",
    "매칭 확정",
    "고객",
    "PATCH /api/client/quotes",
    "app/api/client/quotes/route.ts",
    "어드민·클라이언트",
    "일반기사 견적",
    "final_selected_quote_source=guest",
    "DB 미존재/코드 전용(개념명)",
)
r(
    "DB",
    "driver_quotes",
    "planned_final_price",
    "최종 할인 예정가",
    "연장 전 최종 고객 부담가",
    "bigint",
    "300000",
    "planned_discount_price",
    "견적 제출",
    "시스템",
    "",
    "lib/quote-support-snapshot.ts",
    "확인 필요",
    "",
    "planned_final_price",
    "표시 빈도 낮음",
)
r(
    "DB",
    "applications",
    "quote_deadline_at",
    "견적 마감 시각",
    "자동 마감 기준",
    "timestamptz",
    "2026-05-26T18:00:00+09:00",
    "",
    "신청·연장",
    "시스템",
    "",
    "lib/quote-auction.ts",
    "전체",
    "남은 마감시간",
    "",
    "",
)
r(
    "DB",
    "applications",
    "auto_selected_quote_id",
    "자동 선정 견적 ID",
    "마감 후 시스템 선정(고객 확정 전)",
    "uuid",
    "",
    "",
    "자동마감",
    "시스템",
    "",
    "lib/quote-auction.ts",
    "",
    "",
    "final_selected와 별개",
    "",
)

# --- concepts ---
r(
    "개념",
    "-",
    "선택 견적",
    "선택 견적",
    "매칭 확정 견적·가격 묶음",
    "-",
    "-",
    "selected_price + final_selected_quote_id + type",
    "매칭 확정",
    "고객",
    "PATCH /api/client/quotes",
    "lib/admin-selected-quote-price.ts",
    "전체",
    "선택 견적·매칭견적가",
    "selected_price_type -> selected_price",
    "어드민 selected_price_type 우선",
)
r(
    "개념",
    "-",
    "quote_status",
    "견적 상태",
    "applications.quote_status",
    "text",
    "final_selected",
    "",
    "",
    "",
    "",
    "lib/quote-auction.ts",
    "전체",
    "탭 분기",
    "quote_status",
    "sponsor_status와 별도",
)
r(
    "개념",
    "-",
    "sponsor_status",
    "스폰서 지원 상태",
    "sponsor_support_status / preapproval.status",
    "text",
    "approved",
    "",
    "",
    "",
    "",
    "lib/admin-sponsor-confirmed.ts",
    "전체",
    "지원금 확정/검토중",
    "approved|preapproved",
    "",
)


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "docs" / "quote_support_field_map.csv"
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(HEADER)
        w.writerows(ROWS)
    raw = out.read_bytes()
    assert raw[:3] != b"\xef\xbb\xbf", "BOM detected"
    print(f"Wrote {len(ROWS)} rows -> {out} ({len(raw)} bytes)")


if __name__ == "__main__":
    main()
